package com.henry.tryout.async_program.via_future_in_JDK_02.exception_04;

public class asyncTask_with_exception_and_defalut_solution_01 {
}
